### ISSUE TITLE
Hierarchy of config files

### ISSUE THREAD

**Issue by grahampugh** [ox-it/munki-staging#17]
Hi, just wondering what is the hierarchy of settings from config files, between:
1. `/etc/munki-trello/munki-trello.cfg` (presumably to be changed to `/etc/munki-staging/munki-staging.cfg`?)
2. `./munki-trello.cfg`
3. `--config /path/to/munki-staging.cfg`

**Comment by oucsaw** [comment]
Graham,

The config files should be read in the order:
1. `/etc/munki-staging/munki-staging.cfg`
2. `./munki-staging.cfg`
3. the filename given on the config line, if any

(the README.md file is wrong, as we have updated the configuration file names in the code but in the README - I will fix this shortly).

We are using Python's RawConfigParser to process the files, which will read all the config files it can find in the order above. My assumption is that last match for a variable will win, but the documentation (https://docs.python.org/2/library/configparser.html#rawconfigparser-objects) doesn't actually say this.

I will try to have a look into this and give a more definitive answer as to what will happen if you specify options in more than one file.

I hope this helps,
aaron

**Comment by oucsaw** [comment]
Hi,

We've now updated the documentation to explain better how the configuration file hierarchy actually works.

The summary is that configuration files will be read in the order:
1. `/etc/munki-staging/munki-staging.cfg`
2. `./munki-staging.cfg`
3. the configuration file give on the command line

All configuration files that exist and are readable will be processed; if a
file is missing or unreadable it will not be processed and will not
cause an error. Configuration file sections found in multiple sections
will be folded together, with duplicated settings taking the latest
value found.

(This is a copy and past from the new README.md, which also has a concrete example in).

I hope this helps!

**Comment by grahampugh** [comment]
Thanks Aaron, that makes it clear.

**Comment by grahampugh** [comment]
In case you're interested, I've now got this working as a Docker container:
https://github.com/grahampugh/docker-munki-staging
