### ISSUE TITLE
Retired and To Retired list

### ISSUE THREAD

**Issue by mjung** [ox-it/munki-staging#4]
It would be nice to introduce a fourth catalogue for retired software. 

Bonus feature: move the package and all its metadata to a different munki repository. Use case would be to have the retired software on a cheaper tier of storage or even tape.

**Comment by oucsaw** [comment]
Would you be happy to split this into 2 requests:
- extra catalogue
- package migration

(as I have ideas on how to do the first, but not the second, and think that the second will require more work)

**Comment by mjung** [comment]
Hi.

On 26 June 2015 at 11:16, Aaron Wilson notifications@github.com wrote:

> Would you be happy to split this into 2 requests:
> 
> extra catalogue
> package migration
> 
> (as I have ideas on how to do the first, but not the second, and think that the second will require more work)

Sure. Lets deal with this request only with an extra catalogue with
the current feature set. I will raise a new and more specific feature
request on multi-catalogue support.

M

**Comment by oucsaw** [comment]
Extra catalogs now supported (in fact any number of catalogs > 1 should work).

In branch classes, which needs some more testing and cleaning up

**Comment by oucsaw** [comment]
Support for extra repositories and migration added in commit #12
