### ISSUE TITLE
RSS feeds

### ISSUE THREAD

**Issue by mjung** [ox-it/munki-staging#5]
It would be nice to maintain an RSS feed per catalogue that announces new packages. This feed could be digested by several tools to inform users about new software packages.

**Comment by oucsaw** [comment]
In branch classes, in https://github.com/oucsaw/munki-trello

**Comment by oucsaw** [comment]
.. and now with a pubDate and an icon

**Comment by oucsaw** [comment]
Added in latest merge #12
